### ISSUE TITLE
Support ignoring specific properties?

### ISSUE THREAD

**Issue by PWKad** [bryanrsmith/eslint-plugin-sort-class-members#18]
Question possibly more than a feature request but for instance if I want to have one specific property that I want to ignore (for instance in Aurelia, the `static inject` property) it should be ignorable.  This would allow enforcing all static properties being separate except for the inject property which I like to hug next to the constructor.

**Comment by bryanrsmith** [comment]
I like that configuration, too. Two options:

First (which is what I do), you could target the `inject` property with a separate slot. Something like,

```json
{ "type": "property", "static": true },
{ "name": "inject", "type": "property", "static": true },
{ "name": "constructor" }
```

Second, if you just want to ignore a particular property you should be able to use a regex to match everything except `inject`.

```json
{ "name": "/(?!inject).+/", "type": "property", "static": true },
{ "name": "constructor" }
```

**Comment by bryanrsmith** [comment]
@PWKad Did this work OK for you?

**Comment by PWKad** [comment]
Yes this covered inject for me thanks man been busy should have responded sooner

**Comment by bryanrsmith** [comment]
No worries! Glad it worked for you.
