### ISSUE TITLE
enforce methods to be in alphabetic order

### ISSUE THREAD

**Issue by oprogramador** [bryanrsmith/eslint-plugin-sort-class-members#22]
Maybe it's not a purpose of this module but it would be nice if the following code did not satisfy the rule:

```javascript
class Foo {
  foo() {

  }

  bar() {

  }
}
```

Because `bar` method should before `foo` method to satisfy the alphabetic order.

**Comment by bryanrsmith** [comment]
Sounds reasonable. We can probably add a sort option to each group.

**Comment by bryanrsmith** [comment]
I've been pretty busy lately and I'm not sure if or when I'll get to this. I'd be happy to review a PR if anyone else would like to work on it :-)

**Comment by garyking** [comment]
Is this closed with #44?

**Comment by oprogramador** [comment]
@garyking 

that PR seems to resolve this issue but I haven’t checked that

**Comment by Fuzzyma** [comment]
@oprogramador This is still a needed feature. Is this project dead or is there another reason the PR wasnt merged?
BTW: The typescript version of this pr was just merged into the corresponding plugin (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md)

**Comment by bryanrsmith** [comment]
@Fuzzyma I'm confused. That PR is marked as merged, and the feature is documented. What's the problem?

**Comment by bryanrsmith** [comment]
Does seem like this issue should have been closed, which I'll do now. Do let me know if there's something missing.

**Comment by Fuzzyma** [comment]
Oh - that usually does not happen to me. I am maybe a bit confused today. Thank you for pointing out! Yes it was because the issue was open and I needed exactly that feature
