### ISSUE TITLE
Autofix sort order

### ISSUE THREAD

**Issue by pastelsky** [bryanrsmith/eslint-plugin-sort-class-members#36]
Hey Bryan!

I've have written a [codemod](https://github.com/pastelsky/sort-class-members-codemod) that tries to automatically fix sort ordering of class members defined by this rule. This might be helpful for those integrating this plugin in their projects for the first time.

Would you be willing to accept a PR that adds a link to the same in this projects' Readme?

**Comment by bryanrsmith** [comment]
Looks cool! I'd be happy to.
