### ISSUE TITLE
conventional-private-methods seems to have higher weight than custom groups

### ISSUE THREAD

**Issue by freaktechnik** [bryanrsmith/eslint-plugin-sort-class-members#43]
I have two custom groups:
```js
{
    ...
                          "conventional-private-getters": [
                                {
                                    type: "method",
                                    kind: "get",
                                    accessorPair: false,
                                    name: "/_.+/"
                                }
                            ],
                            "conventional-private-accessor-pairs": [
                                {
                                    type: "method",
                                    accessorPair: true,
                                    name: "/_.+/"
                                }
                            ]
    ...
}
```

And I use them before `conventional-private-methods` in my [configuration](https://github.com/freaktechnik/eslint-plugin-freaktechnik/blob/3644e733662934fa641fbf236a7fafe8b5b48699/index.js#L203-L255), however it will still prefer to move getters to the `conventional-private-methods` group instead of either of the custom groups.

**Comment by bryanrsmith** [comment]
Sorry for the delayed response. I tracked this down to an oversight in the comparer for `accessorPair`, where the match would always fail on `accessorPair: false`. So your conventional-private-getters group would probably work if you removed the `accessorPair` property from the definition. Anyway, I've published version 1.2.2 with a fix. I added a test based on your config, so I think you'll be all set. Let me know if not.

Thanks for the report!
