### ISSUE TITLE
@typescript-eslint/parser v5 compatibility

### ISSUE THREAD

**Issue by EvgenyOrekhov** [bryanrsmith/eslint-plugin-sort-class-members#71]
Upgrading [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser) to v5 causes eslint-plugin-sort-class-members to treat all properties as methods.

Code example:

```ts
export default class Example {
  static staticProperty;
  static staticArrowFunctionProperty = () => {};
  @decorator decoratedProperty = "bar";
  property = "bar";
  arrowFunctionProperty = () => {};
  constructor() {}
}
```

For the above code it starts to give errors like

```text
Expected constructor to come before method decoratedProperty
Expected constructor to come before method property
Expected constructor to come before method arrowFunctionProperty
```

**Comment by svanherk** [comment]
We're seeing these errors as well in JS classes - looks like the linter starts complaining about this after upgrading to the new eslint 8.
