### ISSUE TITLE
Support more TS keywords

### ISSUE THREAD

**Issue by NogaMan** [bryanrsmith/eslint-plugin-sort-class-members#82]
In our project we want to sort abstract fields and their overrides.

For example, for readability we want to place all overridable (abstract) props to the top of the class, then the decorators, then the ordinary fields:
```ts
class BasePoint {
  abstract offset = 0;

  @observable
  coord: number$;
  
  baseCoord: number = 0;

  // ...
}

class OffsettedPoint extends BasePoint {
  override offset = 20;

  // ....
}
```

Currently there is no way to target abstract/override fields, since they are all considered ordinary properties, so we can't insert a group of decorators in between abstract and non-abstract props.

It would be great to support those fields in this plugin

**Comment by NogaMan** [comment]
Come to think of it, `readonly` keyword might also be worth covering

**Comment by bryanrsmith** [comment]
PRs welcome
