### ISSUE TITLE
Class properties with a generic type declaration recognized as methods

### ISSUE THREAD

**Issue by wjhurley** [bryanrsmith/eslint-plugin-sort-class-members#84]
Class properties with a generic type declaration appear to be recognized as methods rather than properties as they should be. I have included my ESLint configuration, an example that recreates the issue, and a screenshot of the ESLint error.

```js
    plugins: [
        'sort-class-members',
    ],
    rules: {
        'sort-class-members/sort-class-members': [
            2,
            {
                accessorPairPositioning: 'getThenSet',
                order: [
                    '[properties]',
                    'constructor',
                    '[methods]',
                ],
            },
        ],
    },
```

```ts
export default abstract class Foo<T> {
    protected abstract readonly _foo: T;

    public readonly bar: string;

    public readonly baz: string;

    protected constructor(bar: string) {
        this.bar = bar;
        this.baz = bar.trim();
    }

    public get data(): Foo<T>['_foo'] {
        if (!this._foo) {
            throw new Error('Something is missing');
        }
        return this._foo;
    }

    protected abstract parse(baz?: string): T;
    protected abstract stringify(): string;
}
```

![image](https://user-images.githubusercontent.com/15939055/231302661-2c61faee-7d22-432a-9e64-16b99ec433f6.png)<br>
![image](https://user-images.githubusercontent.com/15939055/231302708-f56077ab-a4ca-48b3-b552-3e519be058c6.png)

**Comment by bryanrsmith** [comment]
Thanks for the report @wjhurley! Looks like it was actually the `abstract`, which was producing a `TSAbstractPropertyDefinition` node, which was not being included in the type check for properties. I believe I've fixed the issue in 1.17.1, published just now. Let me know how it works for you.
